- hosts: localhost
  tasks:
  - name: check if this is a VM
    shell: "lsusb | grep -q QEMU"
    register: found_qemu
    tags: testing
  - name: setting is_vm
    ansible.builtin.set_fact:
      is_vm: "{{ found_qemu.rc == 0 }}"
    tags: testing

  - name: fixing theme and stuff (1/2)
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/files/xsettings.xml"
      dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
    tags: testing
  - name: fixing theme and stuff (2/2)
    ansible.builtin.copy:
      src: files/xfwm4.mac.xml
      dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
    tags: testing

  - name: setting keyboard configurations to Macbook/Macbook Pro (debconf 1/2)
    ansible.builtin.debconf:
      name: debconf-utils
      question: keyboard-configuration/model
      value: MacBook/MacBook Pro
      vtype: select
    become: true
    tags: Keyboard
  - name: setting keyboard configurations to Macbook/Macbook Pro (debconf 2/2)
    ansible.builtin.debconf:
      name: debconf-utils
      question: keyboard-configuration/modelcode
      value: macbook78
      vtype: string
    become: true
    tags: Keyboard

  - name: copying configured file into ~/.config
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/files/keyboard-layout.xml"
      dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/keyboard-layout.xml
      remote_src: yes
    tags: keyboard-layout.xml

  - name: installing xmodmap (1/2)
    shell: "xmodmap -pke > ~/.Xmodmap"
    tags: NOREPEAT
  - name: fixing Ctrl to Cmd for shortcuts
    ansible.builtin.blockinfile:
      path: ~/.Xmodmap
      append_newline: true
      block: |
        ! bind left command key as another Ctrl key
          remove mod4 = Super_L
          keysym Super_L = Control_L
          add Control = Control_L
      marker: "! {mark} ANSIBLE MANAGED BLOCK"
    tags: NOREPEAT
  - name: loading xmodmap
    shell: "xmodmap ~/.Xmodmap"
    tags: NOREPEAT

  - name: fixing the trackpad speed, tap-to-click, and reverse scrolling(FOR NON VIRTUAL MACHINE 1/2)
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/files/pointers.mac.xml"
      dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/pointers.xml
    when: not is_vm
  - name: fixing the trackpad speed, tap-to-click, and reverse scrolling(FOR NON VIRTUAL MACHINE 2/2)
    ansible.builtin.apt:
      name: xserver-xorg-input-synaptics
      state: absent
    tags: testing
    when: not is_vm
  - name: fixing the trackpad speed, tap-to-click, and reverse scrolling(localhost)
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/files/pointers.QEMU.xml"
      dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/pointers.xml
    tags: testing
    when: is_vm

  - name: closed lid configurations(not for vm)
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/files/xfce4-power-manager.xml"
      dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
    tags: testing
    when: not is_vm

  - name: fixing cycle_windows_key, cycle_reverse_windows_key, and switch_window_key (1/3)
    ansible.builtin.lineinfile:
      path: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
      regexp: '^.* value="cycle_windows_key".*$'
      line: '      <property name="\&lt;Primary\&gt;Tab" type="string" value="cycle_windows_key"/>'
    tags: Cycle_shortcuts
  - name: fixing cycle_windows_key, cycle_reverse_windows_key, and switch_window_key (2/3)
    ansible.builtin.lineinfile:
      path: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
      regexp: '^.* value="cycle_reverse_windows_key".*$'
      line: '      <property name="\&lt;Primary\&gt;\&lt;Shift\&gt;ISO_Left_Tab" type="string" value="cycle_reverse_windows_key"/>'
    tags: Cycle_shortcuts
  - name: fixing cycle_windows_key, cycle_reverse_windows_key, and switch_window_key (3/3)
    ansible.builtin.lineinfile:
      path: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
      regexp: '^.* value="switch_window_key".*$'
      line: '      <property name="\&lt;Primary\&gt;grave" type="string" value="switch_window_key"/>'
    tags: Cycle_shortcuts

  - name: configuring terminal copy-paste shortcuts
    ansible.builtin.blockinfile:
      path: ~/.config/xfce4/terminal/accels.scm
      append_newline: true
      block: |
        (gtk_accel_path "<Actions>/terminal-window/copy" "<Primary>c")
        (gtk_accel_path "<Actions>/terminal-window/paste" "<Primary>v")
    tags: NOREPEAT

  - name: opening sublime to create configuration files
    shell: 'subl'
  - name: sleeping
    ansible.builtin.pause:
      seconds: 5
  - name: pkilling sublime
    shell: 'pkill sublime_text'
    tags: NOREPEAT
  - name: configuring sublime (2/2)
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/files/Preferences.sublime-settings"
      dest: ~/.config/sublime-text/Packages/User/Preferences.sublime-settings
      remote_src: yes
    tags: NOREPEAT

  - name: adding git aliases
    community.general.git_config:
      name: "{{ item.name }}"
      scope: global
      value: "{{ item.value }}"
    loop:
      - { name: alias.co, value: checkout}
      - { name: alias.br, value: branch}
      - { name: alias.ci, value: commit}
      - { name: alias.st, value: status}
      - { name: user.email, value: '{{ ansible_user_id }}@xubuntu'}
      - { name: user.name, value: '{{ ansible_user_id }}'}
    tags: Git

  - name: enabling bluetooth service
    shell: 'sudo systemctl enable bluetooth.service'
    become: true
  - name: start bluetooth service
    shell: 'sudo systemctl start bluetooth.service'
    become: true
  - name: unblocking bluetooth
    shell: 'sudo rfkill unblock bluetooth'
    become: true

  - name: starting the configuration setup for printer
    shell: "cat {{ playbook_dir }}/files/printerconfigs.txt | {{ playbook_dir }}/files/printerconfigs.sh"
    when: not is_vm

  - name: creating .ssh directory
    ansible.builtin.file:
      path: ~/.ssh
      state: directory
      mode: '700'
    tags: ssh-keygen

  - name: generating SSH key to add to github
    community.crypto.openssh_keypair:
      path: ~/.ssh/id_ed25519
      type: ed25519
      comment: "{{ ansible_user_id }}@xubuntu"
    tags: ssh-keygen

