- hosts: localhost
  tasks:
  - name: check if this is a VM
    shell: "lsusb | grep -q QEMU"
    register: found_qemu
    tags: testing
  - name: setting is_vm
    ansible.builtin.set_fact:
      is_vm: "{{ found_qemu.rc == 0 }}"
    tags: testing

  - name: Upgrade the OS
    ansible.builtin.apt:
      upgrade: dist
      force_apt_get: yes
    become: true
    tags: slow

  - name: wifi installation
    ansible.builtin.apt:
      name: bcmwl-kernel-source
      state: present
    when: not is_vm

  - name: installing xmodmap (1/2)
    ansible.builtin.apt:
      name: xkeycaps
      state: present

  - name: setting keyboard configurations to Macbook/Macbook Pro (installing)
    ansible.builtin.apt:
      name: debconf-utils
      state: present
    tags: Keyboard

  - name: installing sublime-text (1/2)
    shell: 'wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null'
  - name: tee-ing into sublime-text.list
    ansible.builtin.copy:
      content: 'deb https://download.sublimetext.com/ apt/stable/'
      dest: /etc/apt/sources.list.d/sublime-text.list
    become: true
  - name: Upgrade all apt packages
    ansible.builtin.apt:
      name: "*"
      state: latest
      force_apt_get: yes
    become: true
    tags: UP
  - name: installing sublime-text (2/2)
    ansible.builtin.apt:
      name: sublime-text
      state: present

  - name: installing git
    ansible.builtin.apt:
      name: git
      state: present

  - name: downloading chrome
    ansible.builtin.get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dest: /tmp/
    tags: chrome
  - name: intsalling chrome
    ansible.builtin.apt:
      deb: /tmp/google-chrome-stable_current_amd64.deb
    become: true
    tags: chrome
  - name: deleting chrome garbage
    ansible.builtin.file:
      path: /tmp/google-chrome-stable_current_amd64.deb
      state: absent
    tags: chrome

  - name: installing bluetooth
    ansible.builtin.apt:
      name: bluez*
      state: present
  - name: installing blueman
    ansible.builtin.apt:
      name: blueman
      state: present

  - name: installing system-config-printer
    ansible.builtin.apt:
      name: system-config-printer
      state: present
    become: true

  - name: virtual machine manager installation
    ansible.builtin.apt:
      name: virt-manager
      state: present
    when: not is_vm

  - name: generating SSH key to add to github
    community.crypto.openssh_keypair:
      path: ~/.ssh/id_ed25519
      type: ed25519
      comment: "{{ ansible_user_id }}@xubuntu"
    tags: ssh-keygen
