- hosts: localhost
  tasks:
  - name: apt update and upgrade
    ansible.builtin.apt:
      update_cache: true
      upgrade: dist
    become: true
    tags: slow

  - name: installing xkeycaps
    ansible.builtin.apt:
      name: xkeycaps
      state: present
    become: true
    tags:
    - xkeycaps
    - mac-keyboard

  - name: setting keyboard configurations to Macbook/Macbook Pro (installing)
    ansible.builtin.apt:
      name: debconf-utils
      state: present
    become: true
    tags:
    - debconf-utils
    - mac-keyboard

  - name: installing sublime-text (1/2)
    ansible.builtin.shell: 'wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null'
    become: true
    tags: sublime
  - name: tee-ing into sublime-text.list
    ansible.builtin.shell: 'echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list'
    become: true
    tags: sublime
  - name: installing sublime-text (2/2)
    ansible.builtin.apt:
      name: sublime-text
      state: present
      update_cache: true
    become: true
    tags: sublime

  - name: installing git
    ansible.builtin.apt:
      name: git
      state: present
    become: true
    tags: git

  - name: downloading chrome
    ansible.builtin.get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dest: /tmp/
    tags: chrome
  - name: installing chrome
    ansible.builtin.apt:
      deb: /tmp/google-chrome-stable_current_amd64.deb
    become: true
    tags: chrome
  - name: deleting chrome garbage
    ansible.builtin.file:
      path: /tmp/google-chrome-stable_current_amd64.deb
      state: absent
    become: true
    tags: chrome

  - name: downloading brave
    ansible.builtin.shell: 'curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg'
    become: true
    tags: brave
  - name: adding brave onto apt/sources.list
    ansible.builtin.shell: 'echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list'
    become: true
    tags: brave
  - name: updating apt repository list and installing brave
    ansible.builtin.apt:
      name: brave-browser
      state: present
      update_cache: true
    become: true
    tags: brave

  - name: installing gnome-tweaks
    ansible.builtin.apt:
      name: gnome-tweaks
      state: present
    become: true
    tags: theme

  - name: installing bluetooth
    ansible.builtin.apt:
      name: bluez*
      state: present
    become: true
    tags: bluetooth
  - name: installing blueman
    ansible.builtin.apt:
      name: blueman
      state: present
    become: true
    tags: bluetooth
  - name: installing bluetooth aac codec for airpod sound
    ansible.builtin.apt_repository:
      repo: ppa:aglasgall/pipewire-extra-bt-codecs
    tags: bluetooth
    become: true
  - name: updating and upgrading to load codec
    ansible.builtin.apt:
      update_cache: true
      upgrade: dist
    become: true
    tags:
    - slow
    - bluetooth

  - name: installing system-config-printer
    ansible.builtin.apt:
      name: system-config-printer
      state: present
    become: true
    tags: printer
  - name: installing cupsd
    ansible.builtin.apt:
      name: cups
      state: present
    become: true
    tags: printer
  - name: purging cups-browsed and its malware
    ansible.builtin.apt:
      name: cups-browsed
      state: absent
      purge: true
    become: true
    tags: cups-browsed

  - name: installing ufw
    ansible.builtin.apt:
      name: ufw
      state: present
    become: true
    tags: ufw

  - name: purging snap
    ansible.builtin.script: "{{ playbook_dir }}/files/remove-snap.sh"
    become: true
    tags: nosnap

  - name: downloading localsend .deb
    ansible.builtin.get_url:
      url: https://github.com/localsend/localsend/releases/download/v1.17.0/LocalSend-1.17.0-linux-x86-64.deb
      dest: /tmp/localsend.deb
    tags: localsend
  - name: installing localsend
    ansible.builtin.apt:
      deb: /tmp/localsend.deb
    become: true
    tags: localsend
  - name: deleting localsend .deb
    ansible.builtin.file:
      path: /tmp/localsend.deb
      state: absent
    become: true
    tags: localsend

  - name: install jetbrains toolbox prerequisites
    ansible.builtin.apt:
      name: "{{ item.name }}"
      state: present
    loop:
      - { name: libfuse2 }
      - { name: libxi6 }
      - { name: libxrender1 }
      - { name: libxtst6 }
      - { name: mesa-utils }
      - { name: libfontconfig }
      - { name: libgtk-3-bin }
    become: true
    tags: jetbrains
  - name: downloading jetbrains toolbox
    ansible.builtin.get_url:
      url: https://download.jetbrains.com/toolbox/jetbrains-toolbox-2.6.2.41321.tar.gz
      dest: /opt/jetbrains.tar.gz
    become: true
    tags: jetbrains
  - name: extracting jetbrains toolbox
    ansible.builtin.unarchive:
      src: /opt/jetbrains.tar.gz
      dest: /opt/
    become: true
    tags: jetbrains
  - name: executing installer for toolbox
    ansible.builtin.script: /opt/jetbrains-toolbox-2.6.2.41321/jetbrains-toolbox
    tags: jetbrains
  - name: cleaning up jetbrains archive (1/2)
    ansible.builtin.file:
      path: /opt/jetbrains-toolbox-2.6.2.41321/
      state: absent
    become: true
    tags: jetbrains
  - name: cleaning up jetbrains archive (2/2)
    ansible.builtin.file:
      path: /opt/jetbrains.tar.gz
      state: absent
    become: true
    tags: jetbrains

  - name: installing virtual machine manager
    ansible.builtin.apt:
      name: virt-manager
      state: present
    become: true
    tags: virtual-machines
  - name: adding quickemu repository
    ansible.builtin.shell: 'sudo apt-add-repository ppa:flexiondotorg/quickemu'
    become: true
    tags: virtual-machines
  - name: updating cache and installing quickemu
    ansible.builtin.apt:
      name: quickemu
      update_cache: true
    become: true
    tags: virtual-machines
  - name: installing quickgui
    ansible.builtin.apt:
      name: quickgui
      update_cache: true
    become: true
    tags: virtual-machines

  - name: installing VLC
    ansible.builtin.apt:
      name: vlc
      state: present
    become: true
    tags:
    - libdvd-pkg
    - optical-drive
  - name: installing sg3-utils (SCSI generic utils)
    ansible.builtin.apt:
      name: sg3-utils
      state: present # did fixed instead in test 1
    become: true
    tags:
    - libdvd-pkg
    - optical-drive
  - name: installing libdvd-pkg (VLC optical drive library)
    ansible.builtin.apt:
      name: libdvd-pkg
      state: present
    become: true
    environment:
      DEBIAN_FRONTEND: noninteractive
    tags:
    - libdvd-pkg
    - optical-drive
  - name: reconfiguring libdvd-pkg for build and installation (1/3)
    ansible.builtin.debconf:
      name: libdvd-pkg
      question: libdvd-pkg/build
      value: "true"
      vtype: boolean
    become: true
    tags:
    - libdvd-pkg
    - optical-drive
  - name: reconfiguring libdvd-pkg for build and installation (2/3)
    ansible.builtin.debconf:
      name: libdvd-pkg
      question: libdvd-pkg/post-invoke_hook-install
      value: "true"
      vtype: boolean
    become: true
    tags:
    - libdvd-pkg
    - optical-drive
  - name: reconfiguring libdvd-pkg for build and installation (3/3)
    ansible.builtin.debconf:
      name: libdvd-pkg
      question: libdvd-pkg/post-invoke_hook-remove
      value: "false"
      vtype: boolean
    become: true
    tags:
    - libdvd-pkg
    - optical-drive

  - name: installing gnome-shell-extensions
    ansible.builtin.apt:
      name: gnome-shell-extensions
      state: present
    become: true
    tags: gnome-extensions
  - name: installing gnome-shell-extension-manager
    ansible.builtin.apt:
      name: gnome-shell-extension-manager
      state: present
    become: true
    tags: gnome-extensions

  - name: installing cpufrequtils (performance tools)
    ansible.builtin.apt:
      name: cpufrequtils
      state: present
    become: true
    tags: performance
  - name: installing preload (performance tools)
    ansible.builtin.apt:
      name: preload
      state: present
    become: true
    tags: performance