- hosts: localhost
  tasks:
  - name: check if this is a VM
    ansible.builtin.shell: "lsusb | grep QEMU"
    ignore_errors: true
    register: found_qemu
    tags: is_vm
  - name: setting is_vm
    ansible.builtin.set_fact:
      is_vm: "{{ found_qemu.rc == 0 }}"
    tags: is_vm

  - name: apt update and upgrade
    ansible.builtin.apt:
      update_cache: true
      upgrade: dist
    become: true
    tags: slow

  - name: installing xkeycaps
    ansible.builtin.apt:
      name: xkeycaps
      state: present
    become: true
    tags: xkeycaps

  - name: setting keyboard configurations to Macbook/Macbook Pro (installing)
    ansible.builtin.apt:
      name: debconf-utils
      state: present
    become: true
    tags: debconf-utils

  - name: installing sublime-text (1/2)
    ansible.builtin.shell: 'wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null'
    become: true
    tags: sublime
  - name: tee-ing into sublime-text.list
    ansible.builtin.shell: 'echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list'
    become: true
    tags: sublime
  - name: installing sublime-text (2/2)
    ansible.builtin.apt:
      name: sublime-text
      state: present
      update_cache: true
    become: true
    tags: sublime

  - name: installing git
    ansible.builtin.apt:
      name: git
      state: present
    become: true
    tags: git

  - name: downloading chrome
    ansible.builtin.get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dest: /tmp/
    tags: chrome
  - name: intsalling chrome
    ansible.builtin.apt:
      deb: /tmp/google-chrome-stable_current_amd64.deb
    become: true
    tags: chrome
  - name: deleting chrome garbage
    ansible.builtin.file:
      path: /tmp/google-chrome-stable_current_amd64.deb
      state: absent
    become: true
    tags: chrome

  - name: downloading brave
    ansible.builtin.shell: 'curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg'
    become: true
    tags: brave
  - name: adding brave onto apt/sources.list
    ansible.builtin.shell: 'echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list'
    become: true
    tags: brave
  - name: updating apt repository list and installing brave
    ansible.builtin.apt:
      name: brave-browser
      state: present
      update_cache: true
    become: true
    tags: brave

  - name: installing gnome-tweaks
    ansible.builtin.apt:
      name: gnome-tweaks
      state: present
    become: true
    tags: theme

  - name: installing bluetooth
    ansible.builtin.apt:
      name: bluez*
      state: present
    become: true
    tags: bluetooth
  - name: installing blueman
    ansible.builtin.apt:
      name: blueman
      state: present
    become: true
    tags: bluetooth

  - name: installing system-config-printer
    ansible.builtin.apt:
      name: system-config-printer
      state: present
    become: true
    tags: printer
  - name: installing cupsd
    ansible.builtin.apt:
      name: cups
      state: present
    become: true
    tags: printer

  - name: installing virtual machine manager
    ansible.builtin.apt:
      name: virt-manager
      state: present
    become: true
    when: not is_vm
    tags: vmm
