- hosts: localhost
  tasks:
  - name: check if this is a VM
    shell: "lsusb | grep -q QEMU"
    register: found_qemu
    tags: testing
  - name: setting is_vm
    ansible.builtin.set_fact:
      is_vm: "{{ found_qemu.rc == 0 }}"
    tags: testing
  ################ FIX: ##################
  - name: unattended upgrade
    shell: "sudo unattended-upgrade"
    tags: slow

  - name: wifi installation
    ansible.builtin.apt:
      name: bcmwl-kernel-source
      state: present
    when: not is_vm

  - name: fixing theme and stuff (1/2)
    ansible.builtin.copy:
      src: files/xsettings.xml
      dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
    tags: testing

  - name: fixing theme and stuff (2/2)
    ansible.builtin.copy:
      src: files/xfwm4.mac.xml
      dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
    tags: testing

  - name: installing xmodmap (1/2)
    ansible.builtin.apt:
      name: xkeycaps
      state: present
  - name: installing xmodmap (1/2)
    shell: "xmodmap -pke > ~/.Xmodmap"
    tags: NOREPEAT
  - name: fixing Ctrl to Cmd for shortcuts
    ansible.builtin.blockinfile:
      path: ~/.Xmodmap
      append_newline: true
      block: |
        ! bind left command key as another Ctrl key
          remove mod4 = Super_L
          keysym Super_L = Control_L
          add Control = Control_L
    tags: NOREPEAT
  - name: loading xmodmap
    shell: "xmodmap ~/.Xmodmap"
    tags: NOREPEAT

  - name: fixing the trackpad speed, tap-to-click, and reverse scrolling(FOR NON VIRTUAL MACHINE 1/2)
    ansible.builtin.copy:
      src: files/pointers.mac.xml
      dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/pointers.xml
  - name: fixing the trackpad speed, tap-to-click, and reverse scrolling(FOR NON VIRTUAL MACHINE 2/2)
    ansible.builtin.apt:
      name: xserver-xorg-input-synaptics
      state: absent
    tags: testing
    when: not is_vm
  - name: fixing the trackpad speed, tap-to-click, and reverse scrolling(localhost)
    ansible.builtin.copy:
      src: files/pointers.QEMU.xml
      dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/pointers.xml
    tags: testing
    when: is_vm